{
 "title": "TIC historique",
 "tags": [ "tic" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   { "name": "bucket", "query": "energy" },
   { "name": "measurement", "query": "enedis-tic" },
   {
    "name": "ADCO",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"${bucket}\",\n  measurement: \"${measurement}\",\n  tag: \"ADCO\",\n  start: -inf\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "IINST",
   "type": "timeseries",
   "description": "IINST[1-3]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  //|> filter(fn: (r) => r[\"host\"] == \"demo-enedis_tic-influxdb-svc-telegraf\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /IINST/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "IMAX",
   "type": "timeseries",
   "description": "IMAX[1-3]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  //|> filter(fn: (r) => r[\"host\"] == \"demo-enedis_tic-influxdb-svc-telegraf\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /IMAX/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Puissance app",
   "type": "timeseries",
   "description": "PAPP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  //|> filter(fn: (r) => r[\"host\"] == \"demo-enedis_tic-influxdb-svc-telegraf\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /PAPP/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PMAX",
   "type": "timeseries",
   "description": "PMAX",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  //|> filter(fn: (r) => r[\"host\"] == \"demo-enedis_tic-influxdb-svc-telegraf\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /PMAX/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "DEMAIN",
   "type": "stat",
   "description": "DEMAIN",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Wh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"DEMAIN\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ISOUSC",
   "type": "stat",
   "description": "ISOUSC",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ISOUSC\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "OPTARIF",
   "type": "stat",
   "description": "OPTARIF",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OPTARIF\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "OPTARIF",
   "type": "stat",
   "description": "OPTARIF",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OPTARIF\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Compteurs",
   "type": "timeseries",
   "description": "Compteurs",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  //|> filter(fn: (r) => r[\"host\"] == \"demo-enedis_tic-influxdb-svc-telegraf\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /BBR/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> difference()\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PTEC",
   "type": "stat",
   "description": "PTEC",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADCO\"] == \"${ADCO}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PTEC\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}