{
 "title": "TIC standard",
 "time": { "from": "2022-06-02T15:56:24.165Z", "to": "2022-06-02T16:33:03.749Z" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   { "name": "bucket", "query": "energy" },
   { "name": "measurement", "query": "enedis-tic-test" },
   {
    "name": "ADSC",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"${bucket}\",\n  measurement: \"${measurement}\",\n  tag: \"ADSC\",\n  start: -inf\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tension efficace",
   "type": "timeseries",
   "description": "URMS[1-3]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  //|> filter(fn: (r) => r[\"host\"] == \"demo-enedis_tic-influxdb-svc-telegraf\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  //|> filter(fn: (r) => r[\"PRM\"] == \"25356150485149\")\n  //|> filter(fn: (r) => r[\"VTIC\"] == \"02\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /URMS/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tension moyenne",
   "type": "timeseries",
   "description": "UMOY[1-3] - Tension moyenne",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /UMOY/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Puissance app. Instantanée soutirée",
   "type": "timeseries",
   "description": "SINSTS - Puissance app. Instantanée\nsoutirée",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  //|> filter(fn: (r) => r[\"host\"] == \"demo-enedis_tic-influxdb-svc-telegraf\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  //|> filter(fn: (r) => r[\"PRM\"] == \"25356150485149\")\n  //|> filter(fn: (r) => r[\"VTIC\"] == \"02\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /SINSTS/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Courant efficace",
   "type": "timeseries",
   "description": "IRMS[1-3] - Courant efficace",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  //|> filter(fn: (r) => r[\"host\"] == \"demo-enedis_tic-influxdb-svc-telegraf\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /IRMS/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Energie active soutirée totale",
   "type": "stat",
   "description": "EAST - Energie active soutirée totale",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Wh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"EAST\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Puissance app. de référence",
   "type": "stat",
   "description": "PREF - Puissance app. de référence",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PREF\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Nom calendrier tarifaire fournisseur",
   "type": "stat",
   "description": "NGTF",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"NGTF\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Numéro de l’index tarifaire en cours",
   "type": "stat",
   "description": "NTARF - Numéro de l’index tarifaire en\ncours",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"NTARF\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Message court",
   "type": "stat",
   "description": "MSG1",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MSG1\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Message ultra court",
   "type": "stat",
   "description": "MSG2",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MSG2\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Puissance app. de coupure",
   "type": "stat",
   "description": "PCOUP - Puissance app. de coupure",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PCOUP\")\n  |> group(columns:[\"_measurement\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Libellé tarif fournisseur",
   "type": "state-timeline",
   "description": "LTARF - Libellé tarif fournisseur en cours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"ADSC\"] == \"${ADSC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"LTARF\")\n  // |> group(columns:[\"_measurement\"])\n  // |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}